"""
backend/app/engine/sanitizer.py

SARTUS Finovate Data Sanitization & Cleaning Engine:
- Auto-detects table bounding boxes, stripping legal disclaimers, titles, and footer notes.
- Eliminates Grand Total, Subtotal, and summary rows to prevent double-counting.
- Normalizes messy international numbering (Indian, European, Tally Cr/Dr, SAP trailing signs).
- Repairs missing account codes, dates, and whitespace anomalies.
"""
import re
from datetime import date
from typing import Any, Dict, List, Optional, Tuple
import pandas as pd
import numpy as np

# Summary markers that distort financial totals
SUMMARY_PATTERNS = re.compile(
    r"^(?:total|grand total|sub total|subtotal|summary|balance b/f|balance c/f|"
    r"closing balance|opening balance|carried forward|brought forward|net total)\b",
    re.IGNORECASE
)

# Junk metadata markers to strip from header/footer regions
METADATA_NOISE_PATTERNS = re.compile(
    r"(?:confidential|page \d+|prepared by|printed on|generated by|internal use|"
    r"all rights reserved|disclaimer|copyright|report date|audited by)",
    re.IGNORECASE
)


class DataSanitizer:
    @classmethod
    def clean_raw_matrix(cls, df: pd.DataFrame) -> pd.DataFrame:
        """
        Takes an arbitrary, dirty DataFrame and executes a 5-step structural scrub.
        """
        if df.empty:
            return df

        # 1. Drop completely empty rows and ghost columns
        cleaned = df.dropna(how="all").dropna(how="all", axis=1).copy()
        if cleaned.empty:
            return cleaned

        # 2. Strip metadata noise rows from top and bottom
        cleaned = cls._strip_noise_rows(cleaned)

        # 3. Clean and deduplicate column names
        cleaned = cls._sanitize_column_headers(cleaned)

        # 4. Strip summary / subtotal rows to prevent double-counting
        cleaned = cls._strip_summary_rows(cleaned)

        # 5. Clean cell whitespace, converting string 'nan', 'null', '—' to None
        cleaned = cls._clean_cell_values(cleaned)

        return cleaned.reset_index(drop=True)

    @classmethod
    def _strip_noise_rows(cls, df: pd.DataFrame) -> pd.DataFrame:
        """Removes metadata banners, confidentiality disclaimers, and printer stamps."""
        if len(df) < 2:
            return df

        drop_indices = []
        for idx in range(len(df)):
            row_str = " ".join([str(v) for v in df.iloc[idx].values if pd.notna(v)])
            # If row contains metadata markers and has very few non-null cells, drop it
            if METADATA_NOISE_PATTERNS.search(row_str) and df.iloc[idx].count() <= 2:
                drop_indices.append(idx)

        if drop_indices:
            df = df.drop(index=drop_indices).reset_index(drop=True)

        return df

    @classmethod
    def _sanitize_column_headers(cls, df: pd.DataFrame) -> pd.DataFrame:
        """Normalizes header whitespace and deduplicates colliding column names."""
        col_counts: Dict[str, int] = {}
        sanitized_cols: List[str] = []

        for idx, col in enumerate(df.columns):
            raw = str(col).strip()
            # If column header is missing or Unnamed
            if not raw or raw.lower().startswith("unnamed:") or raw.lower() in ["nan", "none"]:
                c_clean = f"col_{idx+1}"
            else:
                c_clean = re.sub(r"\s+", "_", raw)

            if c_clean in col_counts:
                col_counts[c_clean] += 1
                sanitized_cols.append(f"{c_clean}_{col_counts[c_clean]}")
            else:
                col_counts[c_clean] = 0
                sanitized_cols.append(c_clean)

        df.columns = sanitized_cols
        return df

    @classmethod
    def _strip_summary_rows(cls, df: pd.DataFrame) -> pd.DataFrame:
        """Strips rows containing Grand Total / Subtotal labels."""
        if df.empty:
            return df

        mask_to_drop = pd.Series(False, index=df.index)
        for col in df.columns[:min(4, len(df.columns))]:
            str_col = df[col].astype(str).str.strip()
            matched = str_col.str.contains(SUMMARY_PATTERNS, na=False)
            mask_to_drop = mask_to_drop | matched

        return df[~mask_to_drop].reset_index(drop=True)

    @classmethod
    def _clean_cell_values(cls, df: pd.DataFrame) -> pd.DataFrame:
        """Cleans cell whitespace and converts stringified null representations."""
        for i in range(df.shape[1]):
            col_series = df.iloc[:, i]
            if col_series.dtype == "object":
                df.iloc[:, i] = col_series.apply(
                    lambda x: None if pd.isna(x) or x is None or str(x).strip().lower() in ["nan", "none", "null", "—", "-", "n/a"] else str(x).strip()
                )
        return df
