"""
backend/app/engine/structural_sanitizer.py

STAGE 2: Structural Sanitization Engine
Guarantees 100% type-safety against NaN floats in empty cells.
"""
import re
from typing import Any, Dict, List, Optional, Tuple
import pandas as pd
import numpy as np

from app.engine.data_understanding import DatasetTopologyProfile, DataUnderstandingEngine

METADATA_NOISE_PATTERNS = re.compile(
    r"(?:confidential|page \d+|prepared by|printed on|generated by|internal use|"
    r"all rights reserved|disclaimer|copyright|report date|audited by)",
    re.IGNORECASE
)


class StructuralSanitizerEngine:
    @classmethod
    def sanitize_matrix(
        cls, 
        df_raw: pd.DataFrame, 
        profile: Optional[DatasetTopologyProfile] = None
    ) -> Tuple[pd.DataFrame, Dict[str, Any]]:
        if df_raw.empty:
            return df_raw, {"original_rows": 0, "cleaned_rows": 0, "banner_rows_stripped": 0, "trailing_rows_stripped": 0}

        if not profile:
            profile = DataUnderstandingEngine.analyze_raw_matrix(df_raw)

        original_row_count = len(df_raw)
        working_df = DataUnderstandingEngine._align_table_headers(df_raw, profile.header_row_index)

        start_row = profile.data_start_row
        end_row = min(profile.data_end_row, len(working_df))
        cropped_df = working_df.iloc[start_row:end_row].copy().reset_index(drop=True)

        cleaned_df = cls._strip_noise_rows(cropped_df)
        cleaned_df = cls._sanitize_headers(cleaned_df)
        cleaned_df = cls._clean_cells(cleaned_df)

        final_df = cleaned_df.dropna(how="all").reset_index(drop=True)

        sanitization_receipt = {
            "original_rows": original_row_count,
            "cleaned_rows": len(final_df),
            "header_row_promoted": profile.header_row_index,
            "banner_rows_stripped": len(profile.metadata_banner_rows),
            "trailing_rows_stripped": max(0, original_row_count - profile.header_row_index - 1 - len(final_df)),
            "topology": profile.topology_type,
        }

        return final_df, sanitization_receipt

    @classmethod
    def _strip_noise_rows(cls, df: pd.DataFrame) -> pd.DataFrame:
        if len(df) < 2:
            return df

        drop_indices = []
        for idx in range(len(df)):
            safe_strings = [str(v) for v in df.iloc[idx].values if pd.notna(v) and str(v).strip() != ""]
            row_str = " ".join(safe_strings)
            if METADATA_NOISE_PATTERNS.search(row_str) and len(safe_strings) <= 2:
                drop_indices.append(idx)

        if drop_indices:
            df = df.drop(index=drop_indices).reset_index(drop=True)

        return df

    @classmethod
    def _sanitize_headers(cls, df: pd.DataFrame) -> pd.DataFrame:
        col_counts: Dict[str, int] = {}
        sanitized: List[str] = []

        for idx, col in enumerate(df.columns):
            c_str = str(col).strip()
            if not c_str or c_str.lower().startswith("unnamed:") or c_str.lower() in ["nan", "none"]:
                c_str = f"col_{idx+1}"

            if c_str in col_counts:
                col_counts[c_str] += 1
                sanitized.append(f"{c_str}_{col_counts[c_str]}")
            else:
                col_counts[c_str] = 0
                sanitized.append(c_str)

        df.columns = sanitized
        return df

    @classmethod
    def _clean_cells(cls, df: pd.DataFrame) -> pd.DataFrame:
        for i in range(df.shape[1]):
            series = df.iloc[:, i]
            if series.dtype == "object":
                df.iloc[:, i] = series.apply(
                    lambda x: None if pd.isna(x) or x is None or str(x).strip().lower() in ["nan", "none", "null", "—", "-", "n/a", "nil"] else str(x).strip()
                )
        return df
