import uuid
from datetime import datetime
from decimal import Decimal
from typing import Optional

from sqlalchemy import Boolean, DateTime, ForeignKey, Numeric, String, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class DecisionRecommendation(Base):
    """
    Represents an actionable strategic recommendation generated by the FinOS decision engine.
    Converts raw financial findings into prescriptive guidance for business leaders.
    """
    __tablename__ = "decision_recommendations"

    # Primary Key (UUID v4)
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
    )

    # Multi-Tenant Isolation Foreign Key
    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        index=True,
        nullable=False,
    )

    # Classification & Priority Tiers
    priority: Mapped[str] = mapped_column(
        String(50),
        default="INFO",
        nullable=False,
    )  # "CRITICAL", "WARNING", "OPPORTUNITY", "INFO"

    category: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
    )  # "CASH_RUNWAY", "MARGIN_RECOVERY", "WORKING_CAPITAL", "OVERHEAD_VARIANCE"

    # Prescriptive Actionable Guidance
    title: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )

    finding_summary: Mapped[str] = mapped_column(
        String(1000),
        nullable=False,
    )

    recommended_action: Mapped[str] = mapped_column(
        String(1000),
        nullable=False,
    )

    # Estimated Monetary Impact (Exact Base-10 Decimal)
    cash_impact_amount: Mapped[Decimal] = mapped_column(
        Numeric(precision=18, scale=4),
        default=Decimal("0.0000"),
        nullable=False,
    )

    # Resolution Tracking Flag
    is_resolved: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False,
    )

    # Server-side Audit Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )