export interface SanitizedPreviewResult {
  headers: string[];
  rows: string[][];
  droppedEmptyCount: number;
  droppedNoiseCount: number;
  isSanitized: boolean;
}

const NOISE_PATTERNS = /^(?:\*+|strictly confidential|internal use only|page \d+|generated by|printed on|report date)/i;
const SUMMARY_PATTERNS = /^(?:total|grand total|subtotal|sub total|closing balance|balance c\/f)/i;

export const Sanitizer = {
  sanitizeFileName(rawName: string): string {
    if (!rawName) return "financial_ledger.csv";
    const parts = rawName.split(".");
    const ext = parts.length > 1 ? parts.pop()?.toLowerCase() : "csv";
    const baseName = parts.join(".");
    let cleaned = baseName
      .replace(/\s*-\s*copy\b/gi, "")
      .replace(/\(\d+\)/g, "")
      .replace(/[\[\](){}]/g, "")
      .replace(/[^\w\s-]/g, "_")
      .trim()
      .replace(/[\s_-]+/g, "_");
    if (!cleaned) cleaned = "financial_document";
    return `${cleaned}.${ext}`;
  },

  sanitizeText(val: string): string {
    if (!val) return "";
    return val.replace(/<[^>]*>?/gm, "").replace(/[\x00-\x1F\x7F]/g, "").replace(/\s+/g, " ").trim();
  },

  sanitizeEmail(val: string): string {
    if (!val) return "";
    return val.toLowerCase().trim();
  },

  sanitizeCurrency(val: string): string {
    if (!val) return "INR";
    const cleaned = val.replace(/[^a-zA-Z]/g, "").toUpperCase();
    return ["INR", "USD", "EUR", "GBP", "AED"].includes(cleaned) ? cleaned : "INR";
  },

  scrubCsvText(rawText: string, maxPreviewRows: number = 6): SanitizedPreviewResult {
    if (!rawText || rawText.trim() === "") {
      return { headers: [], rows: [], droppedEmptyCount: 0, droppedNoiseCount: 0, isSanitized: false };
    }
    const cleanText = rawText.replace(/^\uFEFF/, "");
    const rawLines = cleanText.split(/\r?\n/);
    let droppedEmptyCount = 0;
    let droppedNoiseCount = 0;
    const validLines: string[] = [];

    for (const line of rawLines) {
      const trimmed = line.trim();
      if (!trimmed) {
        droppedEmptyCount++;
        continue;
      }
      if (NOISE_PATTERNS.test(trimmed)) {
        droppedNoiseCount++;
        continue;
      }
      if (SUMMARY_PATTERNS.test(trimmed)) {
        continue;
      }
      validLines.push(trimmed);
    }

    if (validLines.length === 0) {
      return { headers: [], rows: [], droppedEmptyCount, droppedNoiseCount, isSanitized: true };
    }

    const parseCsvRow = (lineStr: string): string[] => {
      const cells: string[] = [];
      let current = "";
      let inQuotes = false;
      for (let i = 0; i < lineStr.length; i++) {
        const ch = lineStr[i];
        if (ch === '"') {
          inQuotes = !inQuotes;
        } else if (ch === "," && !inQuotes) {
          cells.push(current.trim());
          current = "";
        } else {
          current += ch;
        }
      }
      cells.push(current.trim());
      return cells;
    };

    const headers = parseCsvRow(validLines[0]).map((h, idx) => h || `Col_${idx + 1}`);
    const rows = validLines.slice(1, maxPreviewRows + 1).map(parseCsvRow);

    return {
      headers,
      rows,
      droppedEmptyCount,
      droppedNoiseCount,
      isSanitized: droppedEmptyCount > 0 || droppedNoiseCount > 0,
    };
  },
};

export default Sanitizer;
